# Generated by Django 2.2 on 2020-11-03 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.CharField(default='https://www.edmundsgovtech.com/wp-content/uploads/2020/01/default-picture_0_0.png', max_length=500),
        ),
    ]
